#!/usr/bin/env sh

find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +
find . -name 'lib' -type d -prune -exec rm -rf '{}' +
find . -type f -name "package-lock.json" -exec rm -f {} \;
find . -type f -name "yarn.lock" -exec rm -f {} \;
find . -type f -name "pnpm-lock.yaml" -exec rm -f {} \;