#!/bin/bash
PROJECT_ROOT="./packages"

NODE_VERSION=$(node -p -e "require('./lerna.json').version")

echo -e "\033[0;34mCurrent Version: $NODE_VERSION"

for dir in $PROJECT_ROOT/*/; do
    basename=$(basename "$dir")
    if [ $basename != "example" ]; then
        text=$(echo -e "\033[0;32mPublishing the [$basename] packages.")
        echo $text
        yarn workspace @nixjs23n6/$basename publish --force --new-version $NODE_VERSION
    fi
done
